DROP table BK_ORDERDETAILS CASCADE CONSTRAINTS;
DROP table BK_ORDERS CASCADE CONSTRAINTS;
DROP table BK_BOOKS CASCADE CONSTRAINTS;
DROP table BK_AUTHORS CASCADE CONSTRAINTS;
DROP table BK_PUBLISHER CASCADE CONSTRAINTS;
DROP table BK_LANGUAGE CASCADE CONSTRAINTS;
DROP table BK_CATEGORY CASCADE CONSTRAINTS;
DROP table BK_CUSTOMERS CASCADE CONSTRAINTS;

--Customers
CREATE TABLE BK_CUSTOMERS (
    CUST_ID       NUMBER(6)     PRIMARY KEY,
    FIRST_NAME    VARCHAR2(30),
    LAST_NAME     VARCHAR2(30),
    EMAIL         VARCHAR2(50),
    PHONE         VARCHAR2(20),
    ADDRESS  	  VARCHAR2(20), 
    CITY	  VARCHAR2(20), 
    PROVINCE	  VARCHAR2(2), 
    ZIP		  VARCHAR2(6), 
    JOIN_DATE     DATE DEFAULT SYSDATE
);

--Category
CREATE TABLE BK_CATEGORY (
    CATEGORY_ID	   NUMBER(6) 	PRIMARY KEY,
    BOOK_CATEGORY  VARCHAR2(15)
);

--Authors
CREATE TABLE BK_AUTHORS (
    AUTHOR_ID	   NUMBER(6)    PRIMARY KEY,
    LNAME	   VARCHAR2(30),
    FNAME          VARCHAR2(30)
);
   
--Language
CREATE TABLE BK_LANGUAGE (
    LANG_ID       NUMBER(6)     PRIMARY KEY,
    LANGUAGE      VARCHAR2(20)
);   
 
--Publisher
CREATE TABLE BK_PUBLISHER (
    PUB_ID       NUMBER(6)     PRIMARY KEY,
    NAME         VARCHAR2(50),
    ADDRESS      VARCHAR2(100),
    CITY         VARCHAR2(50),
    PHONE	 VARCHAR2(20)
);

--Books
CREATE TABLE BK_BOOKS (
    BOOK_ID        NUMBER     PRIMARY KEY,
    TITLE          VARCHAR2(100),
    AUTHOR_ID      NUMBER(6)  NOT NULL,
    PUB_ID         NUMBER(6),
    CATEGORY_ID    NUMBER(6)  NOT NULL,
    LANG_ID	   NUMBER(6),
    VALUE	   NUMBER(5,2),
    TOTAL_COPIES   NUMBER(3),
    AVAILABLE_COPIES NUMBER(3),
    CONSTRAINT FK_CAT FOREIGN KEY (CATEGORY_ID)
            REFERENCES BK_CATEGORY(CATEGORY_ID),
    CONSTRAINT FK_AUTHOR FOREIGN KEY (AUTHOR_ID)
            REFERENCES BK_AUTHORS(AUTHOR_ID),
    CONSTRAINT FK_PUBLISHER FOREIGN KEY (PUB_ID)
            REFERENCES BK_PUBLISHER(PUB_ID),
    CONSTRAINT FK_LANGUAGE FOREIGN KEY (LANG_ID)
            REFERENCES BK_LANGUAGE(LANG_ID)
);

--Orders
CREATE TABLE BK_ORDERS (
    ORDER_ID     NUMBER(6)     PRIMARY KEY,
    CUST_ID      NUMBER(6)     NOT NULL, 
    ORDER_DATE   DATE DEFAULT SYSDATE,
    DUE_DATE     DATE,
    CONSTRAINT FK_CUSTOMER FOREIGN KEY (CUST_ID)
            REFERENCES BK_CUSTOMERS(CUST_ID)
);

--OrderDetails
CREATE TABLE BK_ORDERDETAILS (
     ORDER_ID    NUMBER(6),
     BOOK_ID     NUMBER(6),
     QUANTITY    NUMBER(3)   NOT NULL,
     UNIT_PRICE  NUMBER(6,2) NOT NULL, 
     TOTAL        NUMBER(6,2),
     RETURN_DATE DATE,
     FINE	 NUMBER(6,2),
     FINE_STATUS CHAR(1) DEFAULT 'N' NOT NULL,
     CONSTRAINT PK_ORDERDETAILS PRIMARY KEY (ORDER_ID, BOOK_ID),
     CONSTRAINT FK_ORDER FOREIGN KEY (ORDER_ID)
         REFERENCES BK_ORDERS(ORDER_ID),
     CONSTRAINT FK_BOOK FOREIGN KEY (BOOK_ID)
         REFERENCES BK_BOOKS(BOOK_ID)
);


DROP SEQUENCE SEQ_BK_CUSTOMER;
DROP SEQUENCE SEQ_BK_BOOK;
DROP SEQUENCE SEQ_BK_ORDERS;
DROP SEQUENCE SEQ_BK_AUTH;
DROP SEQUENCE SEQ_BK_CATEGORY;
DROP SEQUENCE SEQ_BK_LANGUAGE;
DROP SEQUENCE SEQ_BK_PUBLISHER;


CREATE SEQUENCE SEQ_BK_CUSTOMER START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_BK_BOOK START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_BK_ORDERS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_BK_AUTH START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_BK_CATEGORY START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_BK_LANGUAGE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_BK_PUBLISHER START WITH 1 INCREMENT BY 1;


CREATE OR REPLACE TRIGGER TRG_SET_DUE_DATE
BEFORE INSERT ON BK_ORDERS
FOR EACH ROW
BEGIN
    :NEW.DUE_DATE := NVL(:NEW.DUE_DATE, :NEW.ORDER_DATE + 14);
END;
/

CREATE OR REPLACE TRIGGER TRG_BOOK_ORDER_UPDATE
AFTER INSERT ON BK_ORDERDETAILS
FOR EACH ROW
BEGIN
    UPDATE BK_BOOKS
    SET AVAILABLE_COPIES = AVAILABLE_COPIES - 1
    WHERE BOOK_ID = :NEW.BOOK_ID;
END;
/

CREATE OR REPLACE TRIGGER TRG_BOOK_RETURN
AFTER UPDATE OF RETURN_DATE ON BK_ORDERDETAILS
FOR EACH ROW
BEGIN
    -- Only act if RETURN_DATE changed from NULL to a valid date
    IF :OLD.RETURN_DATE IS NULL AND :NEW.RETURN_DATE IS NOT NULL THEN
        UPDATE BK_BOOKS
        SET AVAILABLE_COPIES = AVAILABLE_COPIES + :NEW.QUANTITY
        WHERE BOOK_ID = :NEW.BOOK_ID;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_ORDERDETAILS_TOTAL
BEFORE INSERT OR UPDATE OF QUANTITY, UNIT_PRICE ON BK_ORDERDETAILS
FOR EACH ROW
BEGIN
    :NEW.TOTAL := :NEW.QUANTITY * :NEW.UNIT_PRICE;
END;
/

CREATE OR REPLACE TRIGGER TRG_FINE_STATUS_UPDATE
BEFORE UPDATE OF RETURN_DATE ON BK_ORDERDETAILS
FOR EACH ROW
BEGIN
    IF :OLD.RETURN_DATE IS NULL AND :NEW.RETURN_DATE IS NOT NULL THEN
        :NEW.FINE_STATUS := 'Y';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_FINE_UPDATE
BEFORE UPDATE OF RETURN_DATE ON BK_ORDERDETAILS
FOR EACH ROW
WHEN (NEW.RETURN_DATE IS NOT NULL)
DECLARE
    v_due_date   DATE;
    v_late_days  NUMBER;
BEGIN
    -- Get due date from BK_ORDERS
    SELECT DUE_DATE
    INTO v_due_date
    FROM BK_ORDERS
    WHERE ORDER_ID = :NEW.ORDER_ID;

    -- Calculate late days
    v_late_days := :NEW.RETURN_DATE - v_due_date;

    -- Assign fine directly — NO UPDATE statement!
    IF v_late_days > 0 THEN
        :NEW.FINE := v_late_days * 2;
    ELSE
        :NEW.FINE := 0;
    END IF;

END;
/
