
INSERT INTO BK_CUSTOMERS VALUES (SEQ_BK_CUSTOMER.NEXTVAL, 'Alina', 'Pasat', 'alinapasat@gmail.com','416-444-1212','1 Main St','Toronto','ON','M1A1A1',sysdate-20);
INSERT INTO BK_CUSTOMERS VALUES (SEQ_BK_CUSTOMER.NEXTVAL,'Thomas','King','thomas.king@example.com','555-1001','12 Maple St','Toronto','ON','M1A1A1',SYSDATE-5);
INSERT INTO BK_CUSTOMERS VALUES (SEQ_BK_CUSTOMER.NEXTVAL,'Emily','Clark','emily.clark@example.com','555-1002','88 Oak Ave','Ottawa','ON','K1A0B1',SYSDATE-12);
INSERT INTO BK_CUSTOMERS VALUES (SEQ_BK_CUSTOMER.NEXTVAL,'Daniel','Morgan','daniel.morgan@example.com','555-1003','45 Pine Rd','Hamilton','ON','L8P2A4',SYSDATE-1);
INSERT INTO BK_CUSTOMERS VALUES (SEQ_BK_CUSTOMER.NEXTVAL,'Sophia','Turner','sophia.turner@example.com','555-1004','200 Birch Ln','London','ON','N6A3K7',SYSDATE-10);
INSERT INTO BK_CUSTOMERS VALUES (SEQ_BK_CUSTOMER.NEXTVAL,'Michael','Adams','michael.adams@example.com','555-1005','94 Cedar Ct','Mississauga','ON','L5B1C9',SYSDATE-20);
INSERT INTO BK_CUSTOMERS VALUES (SEQ_BK_CUSTOMER.NEXTVAL,'Olivia','Scott','olivia.scott@example.com','555-1006','77 Elm St','Brampton','ON','L6T3Y1',SYSDATE-14);
INSERT INTO BK_CUSTOMERS VALUES (SEQ_BK_CUSTOMER.NEXTVAL,'William','Harris','will.harris@example.com','555-1007','31 Lakeview Dr','Waterloo','ON','N2L3E5',SYSDATE-3);
INSERT INTO BK_CUSTOMERS VALUES (SEQ_BK_CUSTOMER.NEXTVAL,'Ava','Nelson','ava.nelson@example.com','555-1008','159 Spruce Rd','Kingston','ON','K7L2X3',SYSDATE-9);
INSERT INTO BK_CUSTOMERS VALUES (SEQ_BK_CUSTOMER.NEXTVAL,'James','Baker','james.baker@example.com','555-1009','18 Queen St','Guelph','ON','N1G4T9',SYSDATE-8);
INSERT INTO BK_CUSTOMERS VALUES (SEQ_BK_CUSTOMER.NEXTVAL,'Charlotte','Ward','charlotte.ward@example.com','555-1010','82 River Rd','Barrie','ON','L4N3A2',SYSDATE-16);
INSERT INTO BK_CUSTOMERS VALUES (SEQ_BK_CUSTOMER.NEXTVAL,'Benjamin','Moore','ben.moore@example.com','555-1011','65 King St','Sudbury','ON','P3C1A9',SYSDATE-7);
INSERT INTO BK_CUSTOMERS VALUES (SEQ_BK_CUSTOMER.NEXTVAL,'Isabella','Rogers','isa.rogers@example.com','555-1012','73 Victoria Ave','Windsor','ON','N9A4H5',SYSDATE-2);
INSERT INTO BK_CUSTOMERS VALUES (SEQ_BK_CUSTOMER.NEXTVAL,'Henry','Davis','henry.davis@example.com','555-1013','110 Bay St','Thunder Bay','ON','P7A2T6',SYSDATE-30);
INSERT INTO BK_CUSTOMERS VALUES (SEQ_BK_CUSTOMER.NEXTVAL,'Mia','Cooper','mia.cooper@example.com','555-1014','21 Forest Dr','Peterborough','ON','K9J2T4',SYSDATE-6);
INSERT INTO BK_CUSTOMERS VALUES (SEQ_BK_CUSTOMER.NEXTVAL,'Alexander','Brooks','alex.brooks@example.com','555-1015','94 College St','Oshawa','ON','L1G4X3',SYSDATE-13);
INSERT INTO BK_CUSTOMERS VALUES (SEQ_BK_CUSTOMER.NEXTVAL,'Harper','Stewart','harper.stewart@example.com','555-1016','55 Hillside Rd','Richmond Hill','ON','L4C3K2',SYSDATE-19);
INSERT INTO BK_CUSTOMERS VALUES (SEQ_BK_CUSTOMER.NEXTVAL,'Ethan','Green','ethan.green@example.com','555-1017','44 Sunset Blvd','Markham','ON','L3R2L8',SYSDATE-4);
INSERT INTO BK_CUSTOMERS VALUES (SEQ_BK_CUSTOMER.NEXTVAL,'Amelia','Cole','amelia.cole@example.com','555-1018','199 Willow St','Niagara Falls','ON','L2E3T2',SYSDATE-17);
INSERT INTO BK_CUSTOMERS VALUES (SEQ_BK_CUSTOMER.NEXTVAL,'Logan','Price','logan.price@example.com','555-1019','72 Highland Rd','Kitchener','ON','N2H5K9',SYSDATE-11);
INSERT INTO BK_CUSTOMERS VALUES (SEQ_BK_CUSTOMER.NEXTVAL,'Evelyn','Perry','evelyn.perry@example.com','555-1020','33 Garden Way','St. Catharines','ON','L2R1S3',SYSDATE-15);

INSERT INTO BK_CATEGORY VALUES (SEQ_BK_CATEGORY.NEXTVAL, 'Fiction');
INSERT INTO BK_CATEGORY VALUES (SEQ_BK_CATEGORY.NEXTVAL, 'Non-fiction');
INSERT INTO BK_CATEGORY VALUES (SEQ_BK_CATEGORY.NEXTVAL, 'Mystery');
INSERT INTO BK_CATEGORY VALUES (SEQ_BK_CATEGORY.NEXTVAL, 'Science Fiction');
INSERT INTO BK_CATEGORY VALUES (SEQ_BK_CATEGORY.NEXTVAL, 'Romance');
INSERT INTO BK_CATEGORY VALUES (SEQ_BK_CATEGORY.NEXTVAL, 'Fantasy');
INSERT INTO BK_CATEGORY VALUES (SEQ_BK_CATEGORY.NEXTVAL, 'Biography');
INSERT INTO BK_CATEGORY VALUES (SEQ_BK_CATEGORY.NEXTVAL, 'History');
INSERT INTO BK_CATEGORY VALUES (SEQ_BK_CATEGORY.NEXTVAL, 'Children');
INSERT INTO BK_CATEGORY VALUES (SEQ_BK_CATEGORY.NEXTVAL, 'Self-Help');
INSERT INTO BK_CATEGORY VALUES (SEQ_BK_CATEGORY.NEXTVAL, 'Philosophy');
INSERT INTO BK_CATEGORY VALUES (SEQ_BK_CATEGORY.NEXTVAL, 'Horror');
INSERT INTO BK_CATEGORY VALUES (SEQ_BK_CATEGORY.NEXTVAL, 'Adventure');
INSERT INTO BK_CATEGORY VALUES (SEQ_BK_CATEGORY.NEXTVAL, 'Drama');
INSERT INTO BK_CATEGORY VALUES (SEQ_BK_CATEGORY.NEXTVAL, 'Poetry');
INSERT INTO BK_CATEGORY VALUES (SEQ_BK_CATEGORY.NEXTVAL, 'Art');
INSERT INTO BK_CATEGORY VALUES (SEQ_BK_CATEGORY.NEXTVAL, 'Business');
INSERT INTO BK_CATEGORY VALUES (SEQ_BK_CATEGORY.NEXTVAL, 'Health');
INSERT INTO BK_CATEGORY VALUES (SEQ_BK_CATEGORY.NEXTVAL, 'Cooking');
INSERT INTO BK_CATEGORY VALUES (SEQ_BK_CATEGORY.NEXTVAL, 'Travel');


INSERT INTO BK_AUTHORS VALUES (SEQ_BK_AUTH.NEXTVAL, 'Rowling', 'J.K.');
INSERT INTO BK_AUTHORS VALUES (SEQ_BK_AUTH.NEXTVAL, 'Tolkien', 'J.R.R.');
INSERT INTO BK_AUTHORS VALUES (SEQ_BK_AUTH.NEXTVAL, 'King', 'Stephen');
INSERT INTO BK_AUTHORS VALUES (SEQ_BK_AUTH.NEXTVAL, 'Austen', 'Jane');
INSERT INTO BK_AUTHORS VALUES (SEQ_BK_AUTH.NEXTVAL, 'Orwell', 'George');
INSERT INTO BK_AUTHORS VALUES (SEQ_BK_AUTH.NEXTVAL, 'Hemingway', 'Ernest');
INSERT INTO BK_AUTHORS VALUES (SEQ_BK_AUTH.NEXTVAL, 'Christie', 'Agatha');
INSERT INTO BK_AUTHORS VALUES (SEQ_BK_AUTH.NEXTVAL, 'Brown', 'Dan');
INSERT INTO BK_AUTHORS VALUES (SEQ_BK_AUTH.NEXTVAL, 'Hawking', 'Stephen');
INSERT INTO BK_AUTHORS VALUES (SEQ_BK_AUTH.NEXTVAL, 'Shelley', 'Mary');
INSERT INTO BK_AUTHORS VALUES (SEQ_BK_AUTH.NEXTVAL, 'Lewis', 'C.S.');
INSERT INTO BK_AUTHORS VALUES (SEQ_BK_AUTH.NEXTVAL, 'Lee', 'Harper');
INSERT INTO BK_AUTHORS VALUES (SEQ_BK_AUTH.NEXTVAL, 'Collins', 'Suzanne');
INSERT INTO BK_AUTHORS VALUES (SEQ_BK_AUTH.NEXTVAL, 'Meyer', 'Stephenie');
INSERT INTO BK_AUTHORS VALUES (SEQ_BK_AUTH.NEXTVAL, 'Dostoevsky', 'Fyodor');
INSERT INTO BK_AUTHORS VALUES (SEQ_BK_AUTH.NEXTVAL, 'Murakami', 'Haruki');
INSERT INTO BK_AUTHORS VALUES (SEQ_BK_AUTH.NEXTVAL, 'Atwood', 'Margaret');
INSERT INTO BK_AUTHORS VALUES (SEQ_BK_AUTH.NEXTVAL, 'Coelho', 'Paulo');
INSERT INTO BK_AUTHORS VALUES (SEQ_BK_AUTH.NEXTVAL, 'Martin', 'George R.R.');
INSERT INTO BK_AUTHORS VALUES (SEQ_BK_AUTH.NEXTVAL, 'Tartt', 'Donna');

INSERT INTO BK_LANGUAGE VALUES (SEQ_BK_LANGUAGE.NEXTVAL, 'English');
INSERT INTO BK_LANGUAGE VALUES (SEQ_BK_LANGUAGE.NEXTVAL, 'Spanish');
INSERT INTO BK_LANGUAGE VALUES (SEQ_BK_LANGUAGE.NEXTVAL, 'French');
INSERT INTO BK_LANGUAGE VALUES (SEQ_BK_LANGUAGE.NEXTVAL, 'German');
INSERT INTO BK_LANGUAGE VALUES (SEQ_BK_LANGUAGE.NEXTVAL, 'Japanese');
INSERT INTO BK_LANGUAGE VALUES (SEQ_BK_LANGUAGE.NEXTVAL, 'Portuguese');
INSERT INTO BK_LANGUAGE VALUES (SEQ_BK_LANGUAGE.NEXTVAL, 'Russian');
INSERT INTO BK_LANGUAGE VALUES (SEQ_BK_LANGUAGE.NEXTVAL, 'Italian');
INSERT INTO BK_LANGUAGE VALUES (SEQ_BK_LANGUAGE.NEXTVAL, 'Chinese');
INSERT INTO BK_LANGUAGE VALUES (SEQ_BK_LANGUAGE.NEXTVAL, 'Korean');


INSERT INTO BK_PUBLISHER VALUES (SEQ_BK_PUBLISHER.NEXTVAL, 'Bloomsbury Publishing', '50 Bedford Square', 'London', '212-366-2000');
INSERT INTO BK_PUBLISHER VALUES (SEQ_BK_PUBLISHER.NEXTVAL, 'HarperCollins Publishers', '195 Broadway', 'New York','212-366-2001');
INSERT INTO BK_PUBLISHER VALUES (SEQ_BK_PUBLISHER.NEXTVAL, 'Doubleday', '1745 Broadway', 'New York','212-366-2005');
INSERT INTO BK_PUBLISHER VALUES (SEQ_BK_PUBLISHER.NEXTVAL, 'T. Egerton', '32 Whitehall', 'London','212-366-2008');
INSERT INTO BK_PUBLISHER VALUES (SEQ_BK_PUBLISHER.NEXTVAL, 'Secker Warburg', '20 Vauxhall Bridge Road', 'London','212-366-2004');
INSERT INTO BK_PUBLISHER VALUES (SEQ_BK_PUBLISHER.NEXTVAL, 'Charles Scribner''s Sons', '597 Fifth Avenue', 'New York','212-366-2003');
INSERT INTO BK_PUBLISHER VALUES (SEQ_BK_PUBLISHER.NEXTVAL, 'Collins Crime Club', '8 Grafton Street', 'London','212-366-2006');
INSERT INTO BK_PUBLISHER VALUES (SEQ_BK_PUBLISHER.NEXTVAL, 'Bantam Books', '1745 Broadway', 'New York','212-366-2009');
INSERT INTO BK_PUBLISHER VALUES (SEQ_BK_PUBLISHER.NEXTVAL, 'Little, Brown and Company', '1290 Avenue of the Americas', 'New York','212-366-2050');
INSERT INTO BK_PUBLISHER VALUES (SEQ_BK_PUBLISHER.NEXTVAL, 'McClelland and Stewart', '75 Sherbourne Street', 'Toronto','212-366-2010');
INSERT INTO BK_PUBLISHER VALUES (SEQ_BK_PUBLISHER.NEXTVAL, 'Scholastic Press', '557 Broadway', 'New York','212-366-2020');
INSERT INTO BK_PUBLISHER VALUES (SEQ_BK_PUBLISHER.NEXTVAL, 'HarperTorch', '195 Broadway', 'New York','212-366-2030');
INSERT INTO BK_PUBLISHER VALUES (SEQ_BK_PUBLISHER.NEXTVAL, 'The Russian Messenger', 'Tverskaya Street 25', 'Moscow','212-366-2080');
INSERT INTO BK_PUBLISHER VALUES (SEQ_BK_PUBLISHER.NEXTVAL, 'Shinchosha', '71 Yaraicho', 'Tokyo','212-366-2042');
INSERT INTO BK_PUBLISHER VALUES (SEQ_BK_PUBLISHER.NEXTVAL, 'J.B. Lippincott Co.', '227 South 6th Street', 'Philadelphia','212-366-2045');
INSERT INTO BK_PUBLISHER VALUES (SEQ_BK_PUBLISHER.NEXTVAL, 'Penguin Random House', '1745 Broadway', 'New York','212-366-2085');
INSERT INTO BK_PUBLISHER VALUES (SEQ_BK_PUBLISHER.NEXTVAL, 'Oxford University Press', 'Great Clarendon Street', 'Oxford','212-366-2555');
INSERT INTO BK_PUBLISHER VALUES (SEQ_BK_PUBLISHER.NEXTVAL, 'Simon Schuster', '1230 Avenue of the Americas', 'New York','212-366-2222');
INSERT INTO BK_PUBLISHER VALUES (SEQ_BK_PUBLISHER.NEXTVAL, 'Houghton Mifflin', '125 High Street', 'Boston','212-366-2111');
INSERT INTO BK_PUBLISHER VALUES (SEQ_BK_PUBLISHER.NEXTVAL, 'Vintage Books', '1745 Broadway', 'New York','212-366-2101');

INSERT INTO BK_BOOKS VALUES (SEQ_BK_BOOK.NEXTVAL, 'Harry Potter and the Sorcerer Stone', 1, 1, 1, 1, 12.99, 10, 10);
INSERT INTO BK_BOOKS VALUES (SEQ_BK_BOOK.NEXTVAL, 'The Hobbit', 2, 2, 4, 1, 15.50, 12, 12);
INSERT INTO BK_BOOKS VALUES (SEQ_BK_BOOK.NEXTVAL, 'The Shining', 3, 3, 12, 1, 13.75, 8, 8);
INSERT INTO BK_BOOKS VALUES (SEQ_BK_BOOK.NEXTVAL, 'Pride and Prejudice', 4, 4, 5, 1, 9.50, 7, 7);
INSERT INTO BK_BOOKS VALUES (SEQ_BK_BOOK.NEXTVAL, '1984', 5, 5, 2, 1, 10.25, 10, 10);
INSERT INTO BK_BOOKS VALUES (SEQ_BK_BOOK.NEXTVAL, 'The Old Man and the Sea', 6, 6, 14, 1, 8.75, 9, 9);
INSERT INTO BK_BOOKS VALUES (SEQ_BK_BOOK.NEXTVAL, 'Murder on the Orient Express', 7, 7, 3, 1, 11.25, 11, 11);
INSERT INTO BK_BOOKS VALUES (SEQ_BK_BOOK.NEXTVAL, 'The Da Vinci Code', 8, 3, 3, 1, 14.80, 10, 10);
INSERT INTO BK_BOOKS VALUES (SEQ_BK_BOOK.NEXTVAL, 'A Brief History of Time', 9, 8, 8, 1, 17.99, 10, 10);
INSERT INTO BK_BOOKS VALUES (SEQ_BK_BOOK.NEXTVAL, 'Frankenstein', 10, 16, 12, 1, 9.99, 10, 10);
INSERT INTO BK_BOOKS VALUES (SEQ_BK_BOOK.NEXTVAL, 'The Lion, the Witch and the Wardrobe', 11, 2, 6, 1, 10.99, 10, 10);
INSERT INTO BK_BOOKS VALUES (SEQ_BK_BOOK.NEXTVAL, 'To Kill a Mockingbird', 12, 15, 14, 1, 11.99, 8, 8);
INSERT INTO BK_BOOKS VALUES (SEQ_BK_BOOK.NEXTVAL, 'The Hunger Games', 13, 11, 13, 1, 12.50, 9, 9);
INSERT INTO BK_BOOKS VALUES (SEQ_BK_BOOK.NEXTVAL, 'Twilight', 14, 9, 5, 1, 10.75, 10, 10);
INSERT INTO BK_BOOKS VALUES (SEQ_BK_BOOK.NEXTVAL, 'Crime and Punishment', 15, 13, 14, 7, 13.20, 6, 6);
INSERT INTO BK_BOOKS VALUES (SEQ_BK_BOOK.NEXTVAL, 'Kafka on the Shore', 16, 14, 1, 5, 14.00, 7, 7);
INSERT INTO BK_BOOKS VALUES (SEQ_BK_BOOK.NEXTVAL, 'The Handmaid''s Tale', 17, 10, 1, 1, 13.50, 8, 8);
INSERT INTO BK_BOOKS VALUES (SEQ_BK_BOOK.NEXTVAL, 'The Alchemist', 18, 12, 18, 6, 11.99, 9, 9);
INSERT INTO BK_BOOKS VALUES (SEQ_BK_BOOK.NEXTVAL, 'A Game of Thrones', 19, 8, 6, 1, 15.99, 12, 12);
INSERT INTO BK_BOOKS VALUES (SEQ_BK_BOOK.NEXTVAL, 'The Goldfinch', 20, 9, 14, 1, 16.25, 10, 10);



INSERT INTO BK_ORDERS (ORDER_ID, CUST_ID, ORDER_DATE)
VALUES (SEQ_BK_ORDERS.NEXTVAL, 1, sysdate-20);
INSERT INTO BK_ORDERS (ORDER_ID, CUST_ID, ORDER_DATE)
VALUES (SEQ_BK_ORDERS.NEXTVAL, 2, sysdate-5);
INSERT INTO BK_ORDERS (ORDER_ID, CUST_ID, ORDER_DATE)
VALUES (SEQ_BK_ORDERS.NEXTVAL, 3, sysdate-12);
INSERT INTO BK_ORDERS (ORDER_ID, CUST_ID, ORDER_DATE)
VALUES (SEQ_BK_ORDERS.NEXTVAL, 4, sysdate-1);
INSERT INTO BK_ORDERS (ORDER_ID, CUST_ID, ORDER_DATE)
VALUES (SEQ_BK_ORDERS.NEXTVAL, 5, sysdate-10);

INSERT INTO BK_ORDERDETAILS (ORDER_ID, BOOK_ID, QUANTITY, UNIT_PRICE)
VALUES (1, 1, 2, 20.00);
INSERT INTO BK_ORDERDETAILS (ORDER_ID, BOOK_ID, QUANTITY, UNIT_PRICE, RETURN_DATE)
VALUES (2, 3, 1, 15.50, SYSDATE - 2);
INSERT INTO BK_ORDERDETAILS (ORDER_ID, BOOK_ID, QUANTITY, UNIT_PRICE)
VALUES (3, 5, 1, 25.00);
INSERT INTO BK_ORDERDETAILS (ORDER_ID, BOOK_ID, QUANTITY, UNIT_PRICE, RETURN_DATE)
VALUES (4, 2, 1, 18.99, SYSDATE - 1);
INSERT INTO BK_ORDERDETAILS (ORDER_ID, BOOK_ID, QUANTITY, UNIT_PRICE, RETURN_DATE)
VALUES (5, 4, 3, 12.75, SYSDATE - 10);
