-- LMS Library Management System with lms_ prefix

-- DROP in correct order to avoid FKs

DROP TABLE lms_loan_fines CASCADE CONSTRAINTS;
DROP TABLE lms_loans CASCADE CONSTRAINTS;
DROP TABLE lms_book_copies CASCADE CONSTRAINTS;
DROP TABLE lms_books CASCADE CONSTRAINTS;
DROP TABLE lms_members CASCADE CONSTRAINTS;
DROP TABLE lms_publishers CASCADE CONSTRAINTS;


-- PUBLISHERS
CREATE TABLE lms_publishers (
  publisher_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           VARCHAR2(100) NOT NULL UNIQUE,
  address        VARCHAR2(200),
  phone          VARCHAR2(20),
  email          VARCHAR2(100),
  CONSTRAINT chk_lms_pub_email CHECK (email LIKE '%_@_%._%')
);

-- MEMBERS
CREATE TABLE lms_members (
  member_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name      VARCHAR2(100) NOT NULL,
  member_type    VARCHAR2(20) NOT NULL CHECK (member_type IN ('Student','Faculty','Guest')),
  join_date      DATE DEFAULT SYSDATE NOT NULL,
  email          VARCHAR2(100) UNIQUE
);

-- BOOKS
CREATE TABLE lms_books (
  book_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title          VARCHAR2(200) NOT NULL,
  author         VARCHAR2(100) NOT NULL,
  publisher_id   NUMBER NOT NULL,
  isbn           VARCHAR2(20) NOT NULL UNIQUE,
  pub_year       NUMBER(4) CHECK (pub_year BETWEEN 1450 AND 2900),
  CONSTRAINT fk_lms_book_pub FOREIGN KEY (publisher_id) REFERENCES lms_publishers(publisher_id)
);

-- BOOK COPIES
CREATE TABLE lms_book_copies (
  copy_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  book_id        NUMBER NOT NULL,
  copy_no        NUMBER NOT NULL,
  status         VARCHAR2(20) DEFAULT 'Available' NOT NULL 
                 CHECK (status IN ('Available','Loaned','Lost')),
  CONSTRAINT fk_lms_copy_book FOREIGN KEY (book_id) REFERENCES lms_books(book_id),
  CONSTRAINT uq_lms_copy UNIQUE (book_id, copy_no)
);

-- LOANS
CREATE TABLE lms_loans (
  loan_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  copy_id        NUMBER NOT NULL,
  member_id      NUMBER NOT NULL,
  loan_date      DATE DEFAULT SYSDATE NOT NULL,
  due_date       DATE NOT NULL,
  return_date    DATE,
  CONSTRAINT fk_lms_loan_copy FOREIGN KEY (copy_id) REFERENCES lms_book_copies(copy_id),
  CONSTRAINT fk_lms_loan_member FOREIGN KEY (member_id) REFERENCES lms_members(member_id),
  CONSTRAINT chk_lms_due_after_loan CHECK (due_date > loan_date),
  CONSTRAINT chk_lms_return_after_loan CHECK (return_date IS NULL OR return_date >= loan_date)
);

-- LOAN FINES
CREATE TABLE lms_loan_fines (
  fine_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loan_id        NUMBER NOT NULL UNIQUE,
  fine_amount    NUMBER(6,2) DEFAULT 0 CHECK (fine_amount >= 0),
  paid_flag      VARCHAR2(1) DEFAULT 'N' CHECK (paid_flag IN ('Y','N')),
  CONSTRAINT fk_lms_fine_loan FOREIGN KEY (loan_id) REFERENCES lms_loans(loan_id)
);


 
 -- PUBLISHERS (10 rows)
INSERT INTO lms_publishers (name, address, phone, email) VALUES ('O''Reilly Media', '1005 Gravenstein Hwy N', '707-827-7019', 'info@oreilly.com');
INSERT INTO lms_publishers (name, address, phone, email) VALUES ('Pearson Education', '221B Baker St', '555-1234', 'contact@pearson.com');
INSERT INTO lms_publishers (name, address, phone, email) VALUES ('McGraw-Hill', '1221 Avenue of the Americas', '212-512-2000', 'info@mcgrawhill.com');
INSERT INTO lms_publishers (name, address, phone, email) VALUES ('Springer', 'Tiergartenstrasse 17', '49-6221-4870', 'contact@springer.com');
INSERT INTO lms_publishers (name, address, phone, email) VALUES ('Wiley', '111 River Street', '800-225-5945', 'support@wiley.com');
INSERT INTO lms_publishers (name, address, phone, email) VALUES ('Oxford Press', 'Great Clarendon St', '01865 556767', 'hello@oup.com');
INSERT INTO lms_publishers (name, address, phone, email) VALUES ('MIT Press', 'One Rogers St', '617-253-5646', 'service@mitpress.com');
INSERT INTO lms_publishers (name, address, phone, email) VALUES ('No Starch Press', '245 8th Street', '415-863-9900', 'contact@nostarch.com');
INSERT INTO lms_publishers (name, address, phone, email) VALUES ('Cambridge Press', 'University Printing House', '01223 312393', 'info@cambridge.org');
INSERT INTO lms_publishers (name, address, phone, email) VALUES ('Elsevier', '125 London Wall', '020 7420 4200', 'help@elsevier.com');

-- MEMBERS (10 rows)
INSERT INTO lms_members (full_name, member_type, join_date, email) VALUES ('Alice Johnson', 'Student', sysdate-300, 'alice.j@univ.edu');
INSERT INTO lms_members (full_name, member_type, join_date, email) VALUES ('Bob Smith', 'Faculty', sysdate-400, 'bob.s@univ.edu');
INSERT INTO lms_members (full_name, member_type, join_date, email) VALUES ('Carol White', 'Student', sysdate-330, 'carol.w@univ.edu');
INSERT INTO lms_members (full_name, member_type, join_date, email) VALUES ('David Kim', 'Guest', sysdate-330, 'david.kim@example.com');
INSERT INTO lms_members (full_name, member_type, join_date, email) VALUES ('Eve Adams', 'Faculty', sysdate-400, 'eve.adams@univ.edu');
INSERT INTO lms_members (full_name, member_type, join_date, email) VALUES ('Frank Brown', 'Student', sysdate-350, 'frank.b@univ.edu');
INSERT INTO lms_members (full_name, member_type, join_date, email) VALUES ('Grace Lee', 'Student', sysdate-200, 'grace.lee@univ.edu');
INSERT INTO lms_members (full_name, member_type, join_date, email) VALUES ('Hank Miller', 'Guest', sysdate-320, 'hank.miller@example.com');
INSERT INTO lms_members (full_name, member_type, join_date, email) VALUES ('Ivy Davis', 'Faculty', sysdate-230, 'ivy.d@univ.edu');
INSERT INTO lms_members (full_name, member_type, join_date, email) VALUES ('Jack Thomas', 'Student', sysdate-430, 'jack.t@univ.edu');

-- BOOKS (10 rows)
INSERT INTO lms_books (title, author, publisher_id, isbn, pub_year) VALUES ('Learning SQL', 'Alan Beaulieu', 1, '9780596520830', 2009);
INSERT INTO lms_books (title, author, publisher_id, isbn, pub_year) VALUES ('Database Systems', 'Thomas Connolly', 2, '9780132943260', 2015);
INSERT INTO lms_books (title, author, publisher_id, isbn, pub_year) VALUES ('Modern Operating Systems', 'Andrew Tanenbaum', 3, '9780133591620', 2014);
INSERT INTO lms_books (title, author, publisher_id, isbn, pub_year) VALUES ('Java: The Complete Reference', 'Herbert Schildt', 4, '9780071808552', 2018);
INSERT INTO lms_books (title, author, publisher_id, isbn, pub_year) VALUES ('Clean Code', 'Robert C. Martin', 5, '9780132350884', 2008);
INSERT INTO lms_books (title, author, publisher_id, isbn, pub_year) VALUES ('Artificial Intelligence', 'Stuart Russell', 6, '9780136042594', 2010);
INSERT INTO lms_books (title, author, publisher_id, isbn, pub_year) VALUES ('Introduction to Algorithms', 'Thomas H. Cormen', 7, '9780262033848', 2009);
INSERT INTO lms_books (title, author, publisher_id, isbn, pub_year) VALUES ('Python Crash Course', 'Eric Matthes', 8, '9781593276034', 2015);
INSERT INTO lms_books (title, author, publisher_id, isbn, pub_year) VALUES ('Head First Design Patterns', 'Eric Freeman', 9, '9780596007126', 2004);
INSERT INTO lms_books (title, author, publisher_id, isbn, pub_year) VALUES ('The Pragmatic Programmer', 'Andy Hunt', 10, '9780201616224', 1999);

-- BOOK COPIES (10 rows)
INSERT INTO lms_book_copies (book_id, copy_no) VALUES (1, 1);
INSERT INTO lms_book_copies (book_id, copy_no) VALUES (1, 2);
INSERT INTO lms_book_copies (book_id, copy_no) VALUES (2, 1);
INSERT INTO lms_book_copies (book_id, copy_no) VALUES (3, 1);
INSERT INTO lms_book_copies (book_id, copy_no) VALUES (3, 2);
INSERT INTO lms_book_copies (book_id, copy_no) VALUES (4, 1);
INSERT INTO lms_book_copies (book_id, copy_no) VALUES (5, 1);
INSERT INTO lms_book_copies (book_id, copy_no) VALUES (6, 1);
INSERT INTO lms_book_copies (book_id, copy_no) VALUES (7, 1);
INSERT INTO lms_book_copies (book_id, copy_no) VALUES (8, 1);

-- LOANS (10 rows)
INSERT INTO lms_loans (copy_id, member_id, loan_date, due_date, return_date) VALUES (1, 1, SYSDATE - 10, SYSDATE + 4, NULL);
INSERT INTO lms_loans (copy_id, member_id, loan_date, due_date, return_date) VALUES (2, 2, SYSDATE - 15, SYSDATE - 1, SYSDATE - 2);
INSERT INTO lms_loans (copy_id, member_id, loan_date, due_date) VALUES (3, 3, SYSDATE - 5, SYSDATE + 9);
INSERT INTO lms_loans (copy_id, member_id, loan_date, due_date) VALUES (4, 4, SYSDATE - 12, SYSDATE - 2);
INSERT INTO lms_loans (copy_id, member_id, loan_date, due_date, return_date) VALUES (5, 5, SYSDATE - 20, SYSDATE - 5, SYSDATE - 3);
INSERT INTO lms_loans (copy_id, member_id, loan_date, due_date) VALUES (6, 6, SYSDATE - 2, SYSDATE + 12);
INSERT INTO lms_loans (copy_id, member_id, loan_date, due_date) VALUES (7, 7, SYSDATE - 1, SYSDATE + 13);
INSERT INTO lms_loans (copy_id, member_id, loan_date, due_date) VALUES (8, 8, SYSDATE - 6, SYSDATE + 8);
INSERT INTO lms_loans (copy_id, member_id, loan_date, due_date, return_date) VALUES (9, 9, SYSDATE - 20, SYSDATE - 6, SYSDATE - 1);
INSERT INTO lms_loans (copy_id, member_id, loan_date, due_date) VALUES (10, 10, SYSDATE - 3, SYSDATE + 11);

-- LOAN FINES (10 rows)
INSERT INTO lms_loan_fines (loan_id, fine_amount, paid_flag) VALUES (1, 0, 'Y');
INSERT INTO lms_loan_fines (loan_id, fine_amount, paid_flag) VALUES (2, 2.00, 'Y');
INSERT INTO lms_loan_fines (loan_id, fine_amount, paid_flag) VALUES (3, 0, 'Y');
INSERT INTO lms_loan_fines (loan_id, fine_amount, paid_flag) VALUES (4, 3.50, 'N');
INSERT INTO lms_loan_fines (loan_id, fine_amount, paid_flag) VALUES (5, 0, 'Y');
INSERT INTO lms_loan_fines (loan_id, fine_amount, paid_flag) VALUES (6, 0, 'Y');
INSERT INTO lms_loan_fines (loan_id, fine_amount, paid_flag) VALUES (7, 0, 'Y');
INSERT INTO lms_loan_fines (loan_id, fine_amount, paid_flag) VALUES (8, 1.25, 'N');
INSERT INTO lms_loan_fines (loan_id, fine_amount, paid_flag) VALUES (9, 0, 'Y');
INSERT INTO lms_loan_fines (loan_id, fine_amount, paid_flag) VALUES (10, 0, 'Y');